#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use App\Commands;

require 'vendor/autoload.php';

$application = new Application();

$application->add(new Commands\Build);
$application->add(new Commands\Volume);
$application->add(new Commands\DatabaseBuild);
$application->add(new Commands\DatabaseFfprobe);
$application->add(new Commands\DatabaseTmdb);
$application->add(new Commands\FrontendServe);
$application->add(new Commands\FrontendBuild);

$application->run();
